// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbzqTV5_yiXtHX5zggIFav3NodSsdAZSI',
    appId: '1:1069114837215:web:47dcb3a145508e997d016a',
    messagingSenderId: '1069114837215',
    projectId: 'playere-d7fe2',
    authDomain: 'playere-d7fe2.firebaseapp.com',
    storageBucket: 'playere-d7fe2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzaRPR0fr4FMAToHI9ae4GnnwVv1IHaN8',
    appId: '1:1069114837215:android:5eb2f38026698ef77d016a',
    messagingSenderId: '1069114837215',
    projectId: 'playere-d7fe2',
    storageBucket: 'playere-d7fe2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6g1zYbiWhQPeeSnpTCb1-hWmqqnw6QJI',
    appId: '1:1069114837215:ios:abe249a721016f737d016a',
    messagingSenderId: '1069114837215',
    projectId: 'playere-d7fe2',
    storageBucket: 'playere-d7fe2.appspot.com',
    androidClientId: '1069114837215-cd3jl4s04fjqmt287i024bt6v3l4ouu6.apps.googleusercontent.com',
    iosClientId: '1069114837215-pvi2eoto3d4bpvqvbudsbduqgl0b1sau.apps.googleusercontent.com',
    iosBundleId: 'com.example.playere',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6g1zYbiWhQPeeSnpTCb1-hWmqqnw6QJI',
    appId: '1:1069114837215:ios:abe249a721016f737d016a',
    messagingSenderId: '1069114837215',
    projectId: 'playere-d7fe2',
    storageBucket: 'playere-d7fe2.appspot.com',
    androidClientId: '1069114837215-cd3jl4s04fjqmt287i024bt6v3l4ouu6.apps.googleusercontent.com',
    iosClientId: '1069114837215-pvi2eoto3d4bpvqvbudsbduqgl0b1sau.apps.googleusercontent.com',
    iosBundleId: 'com.example.playere',
  );
}
